iotoast_service:
  image: akyakya/iotoast:latest
  container_name: iotoast
  restart: always
  volumes:
    - $(pwd)/app-prod.properties:/code/app-prod.properties
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro