iotoast_service:
  image: akyakya/iotoast-service:latest
  container_name: iotoast
  restart: always
  ports:
    - 10000:1990
  volumes:
    - ./app-prod.properties:/code/app-prod.properties
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro